### ISSUE TITLE
How to build it

### ISSUE THREAD

**Issue by VimDiezel** [FrancisTheCat/Window_Title_Bar_Remover#1]
I'm having a hard time trying to build it but I get this `link.exe not found`

**Comment by Znarf64** [comment]
Hm, havent seen that before, Id recommend assuring that you installed odin correctly and if you still cant resolve the issue join the odin discord server and ask for help there.

**Comment by Znarf64** [comment]
Btw installing via scoop worked flawlessly for me, but I didnt run into issues compiling from source either

**Comment by Znarf64** [comment]
Have you got a working version of VisualStudio installed? https://odin-lang.org/docs/install

**Comment by Znarf64** [comment]
Just added a release with binaries, hope that helps

**Comment by Lol-Lap** [comment]
> Just added a release with binaries, hope that helps

That did help. Thank you. but I'm having another problem It just doesn't work. I don't know why I pasted the exact same command you had in glaze issue.
```yaml
  - command: "exec 'Path/to/title_remover.exe' title regex Minecraft.*"
    match_title: "Minecraft.*"
```
and still I do nothing.

**Comment by VimDiezel** [comment]
> Just added a release with binaries, hope that helps

That did help. Thank you. but I'm having another problem It just doesn't work. I don't know why I pasted the exact same command you had in glaze issue.
```yaml
  - command: "exec 'C:/Users/Yanking Glyph/Downloads/title_remover_v0.0.1.exe' title regex Control Panel.*"
    match_title: "Control Panel.*"
```
and still I do nothing.

**Comment by Znarf64** [comment]
You need to add quotations around the last argument like so: ... regex 'Control Panel.*'
Also im not sure this regex will match a window with the title "Control Panel", you might have to remove the .\* idk i dont know regex too well. The issue could also be that the control panel is in admin mode. Ill add some debug output to the program tomorow to pin issues like this down

**Comment by VimDiezel** [comment]
> You need to add quotations around the last argument like so: ... regex 'Control Panel.*' Also im not sure this regex will match a window with the title "Control Panel", you might have to remove the .* idk i dont know regex too well. The issue could also be that the control panel is in admin mode. Ill add some debug output to the program tomorow to pin issues like this down

Cool, It's for me, not just for the control panel. It's for everything it's not working. That was an example.

**Comment by VimDiezel** [comment]
What should I try on that you know It's working 100%.

**Comment by Znarf64** [comment]
Minecraft, Minecraft launcher :) and Cactus Image viewer. For testing you could also try it on the file explorer, wich wont work but clearly break

**Comment by VimDiezel** [comment]
> Minecraft, Minecraft launcher :) and Cactus Image viewer. For testing you could also try it on the file explorer, wich wont work but clearly break

```yaml
  - command: "exec 'C:/Users/Yanking Glyph/Downloads/title_remover_v0.0.1.exe' title exact 'This PC'"
    match_title: "This PC"
```
That didn't work 😔

**Comment by Znarf64** [comment]
Oh damn I remember, glaze changes args to lowercase, could you try using the cli directly?

**Comment by VimDiezel** [comment]
It executes but does nothing 
![image](https://github.com/FrancisTheCat/Window_Title_Bar_Remover/assets/120711779/a9cf2ae0-951d-4180-82f9-25e832d10171)

**Comment by VimDiezel** [comment]
The terminal opens, then closes fast when I reopen it.

**Comment by Znarf64** [comment]
Ill add some debug output tomorrow but im off for now, sorry its almost midnight where I live

**Comment by VimDiezel** [comment]
> Ill add some debug output tomorrow but im off for now, sorry its almost midnight where I live

I'm so sorry. I didn't know that. Have a good night.

**Comment by FrancisTheCat** [comment]
Added a new release wich contains some basic logging, if you can send me thel log.txt, I'll hopefully be able to help you

**Comment by Znarf64** [comment]
Added a new release wich contains some basic logging, if you can send me the log.txt, I'll hopefully be able to help you

**Comment by VimDiezel** [comment]
> Added a new release wich contains some basic logging, if you can send me the log.txt, I'll hopefully be able to help you

Well, the WhatsApp One didn't remove the title bar, but it made the border wider, filling the screen.

```
[INFO ] --- [2024-01-12 16:23:13] [main.odin:91:main()] Criterium: Title
[INFO ] --- [2024-01-12 16:23:13] [main.odin:92:main()] Match Mode: Exact
[INFO ] --- [2024-01-12 16:23:13] [main.odin:93:main()] Arg: WhatsApp
[INFO ] --- [2024-01-12 16:23:13] [main.odin:100:main()] Found matching window: WhatsApp
[INFO ] --- [2024-01-12 16:23:13] [main.odin:102:main()] Removed title bar from window
```

**Comment by Znarf64** [comment]
Yeah well thats to be expected, it is a custum title bar, wich cant really be removed easily. Also all windows will be bigger by 7 pixels, idk why, I just use ```resize borders``` to fix it. But Im assuming it works for the Control Panel now?

**Comment by Lol-Lap** [comment]
> Yeah well thats to be expected, it is a custum title bar, wich cant really be removed easily. Also all windows will be bigger by 7 pixels, idk why, I just use `resize borders` to fix it. But Im assuming it works for the Control Panel now?

Yeah, kinda So how to use it in glazewm config

**Comment by VimDiezel** [comment]
> Yeah well thats to be expected, it is a custum title bar, wich cant really be removed easily. Also all windows will be bigger by 7 pixels, idk why, I just use `resize borders` to fix it. But Im assuming it works for the Control Panel now?

Yeah, so how to use it in glazewm config

**Comment by Znarf64** [comment]
> > Yeah well thats to be expected, it is a custum title bar, wich cant really be removed easily. Also all windows will be bigger by 7 pixels, idk why, I just use `resize borders` to fix it. But Im assuming it works for the Control Panel now?
> 
> Yeah, so how to use it in glazewm config

Well thats another can of worms, I hacked glaze by removing the both occurences of .ToLowerInvariant() right here: https://github.com/glzr-io/glazewm/blob/e7d3732eb834407f416a50d112ae4a40b7710d6d/GlazeWM.Domain/UserConfigs/CommandParsingService.cs#L55
This is a hack and im sure it breaks some stuff, but I've decided I dont care as long as it works.
